"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { useAttendance } from "@/components/attendance-provider";
import { useAuth } from "@/components/auth-provider";
import { SectionTabs } from "@/components/section-tabs";
import { Avatar, EmployeeStatusBadge, EmptyState, PageHeading } from "@/components/ui";
import { Icon } from "@/components/icons";
import { employeeStatuses } from "@/data/employees";
import { shiftArrangement, shiftDisplayName } from "@/lib/scheduling";

export default function EmployeesPage() {
  const { canManageEmployees, canDeleteEmployees, role } = useAuth();
  const { employees, shifts, assignments, setEmployeeShift, setEmployeeActive, deleteEmployee } = useAttendance();
  const [search, setSearch] = useState(""); const [department, setDepartment] = useState(""); const [status, setStatus] = useState(""); const [arrangement, setArrangement] = useState("");
  const departments = [...new Set(employees.map((employee) => employee.department))].sort();
  const shiftFor = (employeeId: string) => shifts.find((shift) => shift.id === assignments[employeeId]);
  const filtered = useMemo(() => { const query = search.trim().toLowerCase(); return employees.filter((employee) => { const assignedShift = shifts.find((shift) => shift.id === assignments[employee.id]); return (!query || [employee.name, employee.email, employee.id, employee.role].some((value) => value.toLowerCase().includes(query))) && (!department || employee.department === department) && (!status || employee.status === status) && (!arrangement || shiftArrangement(assignedShift) === arrangement); }); }, [employees, shifts, assignments, search, department, status, arrangement]);
  const remove = (id: string, name: string) => { if (window.confirm(`Delete ${name}? Their historical records will be retained.`)) deleteEmployee(id); };
  const stats = role === "manager" ? [{ label: "Assigned team", value: employees.length, tone: "blue" }, { label: "Active", value: employees.filter((item) => item.status === "Active").length, tone: "emerald" }, { label: "Inactive", value: employees.filter((item) => item.status === "Inactive").length, tone: "slate" }] : [{ label: "Total employees", value: employees.length, tone: "blue" }, { label: "Active", value: employees.filter((item) => item.status === "Active").length, tone: "emerald" }, { label: "Inactive", value: employees.filter((item) => item.status === "Inactive").length, tone: "slate" }, { label: "Terminated", value: employees.filter((item) => item.status === "Terminated").length, tone: "rose" }];
  return <div className="people-reference space-y-5">
    <PageHeading eyebrow="People" title={role === "manager" ? "My team" : "Employees"} description={role === "manager" ? "View your assigned team members only." : "Manage your workforce and employee records."} action={canManageEmployees ? <Link className="btn-primary gap-2" href="/employees/new"><span className="text-lg leading-none">+</span> Add Employee</Link> : undefined} />
    <section className={`grid grid-cols-2 gap-4 ${role === "manager" ? "lg:grid-cols-3" : "lg:grid-cols-4"}`}>{stats.map((item) => <article className="people-stat" key={item.label}><span className={`people-stat-icon people-stat-${item.tone}`}><Icon name="people" /></span><div><p>{item.label}</p><b>{item.value}</b></div></article>)}</section>
    {role !== "manager" && <div className="flex items-end gap-5"><div className="min-w-0 flex-1"><SectionTabs items={[{ href: "/employees", label: "Employees" }, { href: "/lifecycle", label: "Lifecycle" }, { href: "/departments", label: "Departments" }]} /></div>{canManageEmployees && <Link className="btn-primary mb-2 gap-2" href="/employees/new"><span className="text-lg">+</span>Add employee</Link>}</div>}
    <section className="panel overflow-hidden">
      <div className="border-b border-slate-100 p-4 sm:p-5"><div className="filter-bar !p-0"><label className="search-field"><Icon name="search" className="h-4 w-4" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search employees" /></label>{role !== "manager" && <label className="filter-field"><span>Department</span><select value={department} onChange={(event) => setDepartment(event.target.value)}><option value="">All departments</option>{departments.map((item) => <option key={item}>{item}</option>)}</select></label>}<label className="filter-field"><span>Status</span><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">All statuses</option>{employeeStatuses.map((item) => <option key={item}>{item}</option>)}</select></label>{role !== "manager" && <label className="filter-field"><span>Arrangement</span><select value={arrangement} onChange={(event) => setArrangement(event.target.value)}><option value="">All arrangements</option><option>Office</option><option>Remote</option><option>Hybrid</option></select></label>}</div></div>
      <div className="panel-heading"><div><h2 className="section-title">Employee directory</h2><p className="section-copy">{filtered.length} of {employees.length} visible employees</p></div></div>
      {filtered.length === 0 ? <EmptyState title="No employees found" description="Try adjusting your authorized search or filters." /> : <div className="table-wrap"><table className="people-table min-w-[1080px]"><thead><tr><th>Employee</th><th>Department</th><th>Role / Position</th><th>Shift</th><th>Work arrangement</th><th>Status</th><th>{canManageEmployees ? "Actions" : "Profile"}</th></tr></thead><tbody>{filtered.map((employee) => { const assignedShift = shiftFor(employee.id); return <tr key={employee.id}><td><Link href={`/employees/${encodeURIComponent(employee.id)}`} className="flex items-center gap-3"><Avatar initials={employee.initials} /><div><p className="font-semibold text-slate-900">{employee.name}</p><p className="text-xs text-slate-500">{employee.id} · {employee.email}</p></div></Link></td><td>{employee.department}</td><td>{employee.role}</td><td>{canManageEmployees ? <select aria-label={`Shift for ${employee.name}`} className="compact-select max-w-48" value={assignments[employee.id] || ""} onChange={(event) => setEmployeeShift(employee.id, event.target.value)}><option value="">Unassigned</option>{shifts.map((shift) => <option key={shift.id} value={shift.id}>{shiftDisplayName(shift)}</option>)}</select> : assignedShift ? shiftDisplayName(assignedShift) : "Unassigned"}</td><td><span className="arrangement-badge">{shiftArrangement(assignedShift)}</span></td><td><EmployeeStatusBadge status={employee.status} /></td><td><div className="flex items-center gap-2">{canManageEmployees ? <><Link className="table-action" href={`/employees/${encodeURIComponent(employee.id)}/edit`}>Edit</Link><button className="table-action" onClick={() => setEmployeeActive(employee.id, employee.status !== "Active")}>{employee.status === "Active" ? "Deactivate" : "Activate"}</button>{canDeleteEmployees && <button className="table-action text-rose-600" onClick={() => remove(employee.id, employee.name)}>Delete</button>}</> : <Link className="table-action" href={`/employees/${encodeURIComponent(employee.id)}`}>View</Link>}</div></td></tr>; })}</tbody></table></div>}
    </section>
  </div>;
}
